[package]
name = "overlinejunior/link"
description = "Extremely simple networking library that allows you to create shared modules for remotes that are the same between both the client and server."
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"
author = "Over"
exclude = ["selene.toml", "roblox.toml"]


[dependencies]
